# Changes here will be overwritten by Copier
_commit: 42057e0
_src_path: https://github.com/python-project-templates/base.git
add_extension: python
email: t.paine154@gmail.com
github: csp-community
project_description: Miscellaneous commands for csp-bot
project_name: csp bot commands
python_version_primary: '3.11'
team: the csp-bot-commands authors
