__all__ = (
    "a_or_an",
    "ADJECTIVES",
    "COLORS",
    "FISH",
    "SHAKEPEREAN_MODIFIERS_ONE",
    "SHAKEPEREAN_MODIFIERS_TWO",
    "SHAKESPEREAN_NOUNS",
    "RANDOM_SINGULAR_NOUNS",
    "MONEY",
    "ICELANDIC",
    "GERMAN",
    "DUNE",
    "BUSH",
    "DRINKING_ESTABLISHMENTS",
    "COCKTAILS",
    "BEER",
    "WINE",
    "WHISKEY",
    "YOGI",
    "TOLKIEN",
    "FORTUNE",
    "PRATCHETT",
    "WILDE",
    "NIETZSCHE",
    "TWAIN",
    "ZEN",
    "STOIC",
    "CHURCHILL",
    "CONFUCIUS",
    "STARWARS",
    "HITCHHIKER",
    "HEMINGWAY",
    "DAD_JOKES",
    "CHUCK_NORRIS",
    "SOVIET",
    "CONSPIRACY",
    "MAGIC8",
    "COMPLIMENTS",
    "LATIN",
    "PIRATE",
    "CORPORATE",
    "MOTIVATIONAL",
    "HAIKU",
    "PROGRAMMING_JOKES",
)


def a_or_an(next_word):
    first_letter = next_word[0]
    if first_letter.lower() in ("a", "e", "i", "o", "u"):
        return "an"
    return "a"


ADJECTIVES = ()
COLORS = (
    "pink",
    "light pink",
    "dark pink",
    "hot pink",
    "violet",
    "light violet",
    "dark violet",
    "purple",
    "light purple",
    "dark purple",
    "magenta",
    "fuchsia",
    "plum",
    "lavender",
    "light red",
    "dark red",
    "red",
    "crimson",
    "salmon",
    "tomato",
    "orange",
    "gold",
    "khaki",
    "yellow",
    "light yellow",
    "dark yellow",
    "lemon yellow",
    "maroon",
    "brown",
    "sienna",
    "chocolate",
    "tan",
    "blue",
    "light blue",
    "dark blue",
    "slate blue",
    "indigo",
    "midnight blue",
    "navy",
    "royal blue",
    "sky blue",
    "powder blue",
    "teal",
    "cyan",
    "sea green",
    "tuquoise",
    "aquq",
    "aquamarine",
    "green",
    "dark green",
    "light green",
    "olive green",
    "forest green",
    "sea green",
    "lime green",
    "chartreuse",
    "white",
    "beige",
    "snow white",
    "ivory",
    "grey",
    "light grey",
    "dark grey",
    "slate grey",
    "silver",
    "black",
)

FISH = (
    "albacore",
    "amberjack",
    "anchovy",
    "angelfish",
    "anglerfish",
    "arctic char",
    "barracuda",
    "barramundi",
    "bass",
    "blackfin tuna",
    "blobfish",
    "blowfish",
    "bluefin tuna",
    "bonefish",
    "bonito",
    "bream",
    "carp",
    "catfish",
    "clownfish",
    "cod",
    "cowfish",
    "dogfish",
    "dorado",
    "dory",
    "eagle ray",
    "eel",
    "electric eel",
    "fire goby",
    "flathead catfish",
    "flounder",
    "flying fish",
    "frogfish",
    "goatfish",
    "goby",
    "goldfish",
    "gourami",
    "grouper",
    "guppy",
    "haddock",
    "hagfish",
    "halibut",
    "herring",
    "horsefish",
    "jackfish",
    "jawfish",
    "jewelfish",
    "koi",
    "lamprey",
    "largemouth bass",
    "lionfish",
    "loach",
    "mackerel",
    "mahi-mahi",
    "manta ray",
    "minnow",
    "moray eel",
    "mudfish",
    "mudskipper",
    "oarfish",
    "parrotfish",
    "perch",
    "pollock",
    "porgy",
    "pufferfish",
    "rainbow trout",
    "ray",
    "remora",
    "salmon",
    "sardine",
    "sculpin",
    "sea bass",
    "sea bream",
    "sea dragon",
    "sea snail",
    "seahorse",
    "shark",
    "skate",
    "skipjack tuna",
    "smelt",
    "snakehead",
    "sockeye salmon",
    "sole",
    "spearfish",
    "sprat",
    "stingray",
    "striped bass",
    "sturgeon",
    "sunfish",
    "swordfish",
    "tarpon",
    "tetra",
    "tiger shark",
    "tilapia",
    "tilefish",
    "toadfish",
    "triggerfish",
    "trout",
    "tuna",
    "wahoo",
    "walleye",
    "wrasse",
    "yellowfin tuna",
    "yellowtail",
    "zebrafish",
)

SHAKEPEREAN_MODIFIERS_ONE = (
    "artless",
    "bawdy",
    "beslubbering",
    "bootless",
    "churlish",
    "cockered",
    "clouted",
    "craven",
    "currish",
    "dankish",
    "dissembling",
    "droning",
    "errant",
    "fawning",
    "fobbing",
    "froward",
    "frothy",
    "gleeking",
    "goatish",
    "gorbellied",
    "impertinent",
    "infectious",
    "jarring",
    "joggerheaded",
    "lumpish",
    "mammering",
    "mangled",
    "mewling",
    "paunchy",
    "pribbling",
    "puking",
    "puny",
    "rank",
    "reeky",
    "roguish",
    "ruftish",
    "saucy",
    "spleeny",
    "spongy",
    "surly",
    "tottering",
    "unmuzzled",
    "vain",
    "venomed",
    "villainous",
    "warped",
    "wayward",
    "weedy",
    "yeasty",
)

SHAKEPEREAN_MODIFIERS_TWO = (
    "base-court",
    "bat-forling",
    "beef-witted",
    "beetle-headed",
    "boil-brained",
    "clapper-clawed",
    "clay-brained",
    "common-kissing",
    "crook-pated",
    "dismal-dreaming",
    "dizzy-eyed",
    "doghearted",
    "dread-bolted",
    "earth-vexing",
    "elf-skinned",
    "fat-kidneyed",
    "fen-sucked",
    "flap-mothed",
    "fly-bitten",
    "folly-fallen",
    "fool-born",
    "fill-gorged",
    "guts-griping",
    "half-faced",
    "hasty-witted",
    "hedge-born",
    "hell-hated",
    "idle-headed",
    "ill-breeding",
    "ill-nurtured",
    "knotty-pated",
    "milk-livered",
    "motley-minded",
    "onion-eyed",
    "plume-plucked",
    "pottle-deep",
    "pox-marked",
    "reeling-ripe",
    "rough-hewn",
    "rude-growing",
    "rump-faced",
    "shard-borne",
    "sheep-biting",
    "spur-galled",
    "swag-bellied",
    "tardy-gaited",
    "tickle-brained",
    "toad-spotted",
    "unchin-snoted",
    "weather-bitten",
)

SHAKESPEREAN_NOUNS = (
    "apple-john",
    "baggage",
    "barnacle",
    "bladder",
    "boar-pig",
    "bugbear",
    "bum-bailey",
    "canket-blossom",
    "clack-dish",
    "clotpole",
    "coxcomb",
    "codpiece",
    "death-token",
    "dewberry",
    "flap-dragon",
    "flax-wench",
    "flirt-gill",
    "foot-licker",
    "futilarrian",
    "giglet",
    "gudgeon",
    "haggard",
    "harpy",
    "hedge-pig",
    "horn-beast",
    "hugger-mugger",
    "joithead",
    "lewduster",
    "lout",
    "maggot-pie",
    "malt-worm",
    "mammet",
    "measle",
    "minnow",
    "miscreant",
    "moldwarp",
    "mumble-news",
    "nut-hook",
    "pigeon-egg",
    "pignut",
    "puttock",
    "pumbion",
    "ratsbane",
    "scut",
    "skainsmate",
    "strumpot",
    "varlot",
    "vassal",
    "wheyface",
    "wagtail",
)

RANDOM_SINGULAR_NOUNS = (
    "CD",
    "USB drive",
    "VHS",
    "air freshener",
    "bag",
    "bag of chalk",
    "bag of packing peanuts",
    "balloon",
    "bed",
    "blanket",
    "blouse",
    "book",
    "bookmark",
    "boom box",
    "bottle",
    "bottle cap",
    "bouquet of flowers",
    "bow",
    "bowl",
    "box",
    "bracelet",
    "buckle",
    "camera",
    "candle",
    "candy wrapper",
    "car",
    "cell phone",
    "chair",
    "charger",
    "checkbook",
    "cinder block",
    "clamp",
    "clay pot",
    "clock",
    "computer",
    "cookie jar",
    "cork",
    "couch",
    "credit card",
    "cup",
    "desk",
    "doll",
    "drawer",
    "drill press",
    "eraser",
    "flag",
    "fork",
    "fridge",
    "fruit basket",
    "glass",
    "glow stick",
    "greeting card",
    "hair brush",
    "hair tie",
    "helmet",
    "house",
    "ice cube tray",
    "iphone",
    "ipod",
    "key chain",
    "keyboard",
    "knife",
    "lamp",
    "lamp shade",
    "magnet",
    "mirror",
    "model car",
    "monitor",
    "mop",
    "mouse pad",
    "mp3 player",
    "nail file",
    "newspaper",
    "paint brush",
    "pair of glasses",
    "pair of headphones",
    "pair of leg warmers",
    "pair of nail clippers",
    "pair of pants",
    "pair of shoes",
    "pair of socks",
    "pair of speakers",
    "pair of sun glasses",
    "pen",
    "pencil",
    "perfume",
    "phone",
    "photo album",
    "piano",
    "picture frame",
    "pillow",
    "plastic fork",
    "plate",
    "playing card",
    "pool stick",
    "purse",
    "radio",
    "remote",
    "ring",
    "rubber band",
    "rubber duck",
    "rug",
    "rusty nail",
    "sailboat",
    "sandal",
    "scotch tape",
    "set of keys",
    "set of tweezers",
    "sharpie",
    "shawl",
    "shirt",
    "shovel",
    "sketch pad",
    "slipper",
    "soda can",
    "sofa",
    "spindle of thread",
    "sponge",
    "spoon",
    "spring",
    "sticky note",
    "stop sign",
    "table",
    "tablet",
    "teacup",
    "television",
    "thermometer",
    "thermostat",
    "tissue box",
    "toe ring",
    "toilet",
    "toothbrush",
    "towel",
    "toy truck",
    "tree",
    "tube of toothpaste",
    "tv",
    "vase",
    "video game",
    "wagon",
    "wallet",
    "washing machine",
    "watch",
    "water bottle",
    "zipper",
)

MONEY = (
    "$1 bills",
    "pennies",
    "nickels",
    "dimes",
    "loonies",
    "stright cash money",
    "gold bullion",
    "onion futures",
    "tulips",
    "rare beanie babies",
    "bitcoin",
    "dogecoin",
)

ICELANDIC = (
    "Af góðu upphafi vonast góður endir.",
    "Af óskum eru allir eins ríkir",
    "Allir vilja herrann vera, en enginn sekkinn bera",
    "Aldrei er góð vísa of oft kveðin",
    "Árinni kennir illur ræðari",
    "Á misjöfnu þrífast börnin bes",
    "Ber er hver að baki nema sér bróður eigi",
    "Betra er að vera fátækr og heill, enn ríkr og vanheill",
    "Betra er einn að vera, en illan stallbróður hafa",
    "Bezt er að hætta hvörjum leik , meðan vel fer",
    "Brennt barn forðast eldinn",
    "Ef ábóti teninga a sér ber, oss munkum leyft ao tefla er.",
    "Eftir því sem gamlir fuglar sungu, kvökuðu þeir ungu",
    "Einki er so illt, táð er ikki gott firi okkurt",
    "Engum flýgur sofanda steikt gæs i munn",
    "Garðr er granna sættir",
    "Guð hjálpar þeim sem hjálpa sér sjálfir",
    "Góð orð finna góðan samastað",
    "Vitur maður breytir hugum sínum, heimskingi vill aldrei",
    "Hver er sinnar gæfu smiður",
    "Kemst þó hægt fari",
    "Kom ei of opt til vina þinna, svo þá væmi ekki við þér",
    "Kornbarn, drukkin maðr og dárinn segja sannleikann",
    "Láttu ekki happ ur hendi sleppa",
    "Líkt á við líkt Líkt",
    "Linur bartskeri gjörir fúin sár",
    "Margr lækr smár gjörir stórar ár",
    "Náttin er manns óvinur",
    "Ofleyfingjarnir bregðask mér mest",
    "Oft hafa fagrar hnetur fúinn kjarna",
    "Þá mér klær, þarf ég að klóra mér",
    "þar liggur hundurinn grafinn",
    "þegar neyðin er hærst, er hjálpin nærst",
    "þó hinn fátæki tali hyggiliga, vill það enginn heyra",
    "Ragur maður fíflar aldrei fríða konu",
    "Sá er fuglinn verstur, sem í sjálfs síns hreiður dritar",
    "Sjaldan er ein báran stök",
    "Sjaldan fellur eplið langt frá eikini",
    "Spónasmiða börn eiga oft versta spæni",
    "Sinn er siður í landi hverju",
    "Sá vinnur sitt mál, sem þráastur er",
    "Sá fær opt æruna virðinguna sem minnst is fær opt æruna sækist eptir henni",
    "Sæll er sá, sem lætr sér annars víti að varnaði verða",
    "Vitið kemr ei fyrir árin",
)

GERMAN = (
    "Streichholzschächtelchen - Translation: Matchbox",
    "Lebensabschnittsgefährte - Translation: Domestic partner",
    "Freundschaftsbeziehungen - Translation: Friendship relationships",
    "Unabhängigkeitserklärungen - Translation: Declarations of Independence",
    "Nahrungsmittelunverträglichkeit - Translation: Food intolerance",
    "Arbeiterunfallverischerungsgesetz - Translation: Workers' Compensation Act",
    "Rechtsschutzversicherungsgesellschaften - Translation: Legal expenses insurance companies",
    "Donaudampfschiffahrtsgesellschaftskapitän - Translation: Danube Steamship Company Captain",
    "Betäubungsmittelverschreibungsverordnung - Translation: Narcotics Prescription Ordinance",
    "Massenkommunikationsdienstleistungsunternehmen - Translation: Mass Communications Services Company",
    "Neunhundertneunundneunzigtausendneunhundertneunundneunzig - Translation: Nine hundred and ninety nine thousand nine hundred and ninety nine",
    "Rindfleischetikettierungsüberwachungsaufgabenübertragungsgesetz - Translation: Delegation transfer law for the labeling of beef in order to monitor task transfers",
    "Grundstücksverkehrsgenehmigungszuständigkeitsübertragungsverordnung - Translation: Regulation on the delegation of authority concerning land conveyance permissions",
    "Donaudampfschiffahrtselektrizitätenhauptbetriebswerkbauunterbeamtengesellschaft - Translation: Danube Steamship Electricity Main Plant Construction Suboffice Company",
    "Rinderkennzeichnungsfleischetikettierungsüberwachungsaufgabenübertragungsgesetz - Translation: Delegation transfer law for cattle labeling and beef labeling supervision duties",
)


DUNE = (
    "Not the blood, sir. But all of a man’s water, ultimately, belongs to his people—to his tribe. It’s a necessity when you live near the Great Flat. All water’s precious there, and the human body is composed of some seventy percent water by weight. A dead man, surely, no longer requires that water.",
    "The willow submits to the wind and prospers until one day it is many willows—a wall against the wind. This is the willow’s purpose.",
    "Sir, I honor and respect the personal dignity of any man who respects my dignity. I am indeed indebted to you. And I always pay my debts. If it is your custom that this knife remain sheathed here, then it is so ordered—by me. And if there is any other way we may honor the man who died in our service, you have but to name it.",
    "The concept of progress acts as a protective mechanism to shield us from the terrors of the future.",
    "Deep in the human unconscious is a pervasive need for a logical universe that makes sense, But the real universe is always one step beyond logic.",
    "Anything outside yourself, this you can see and apply your logic to it. But it’s a human trait that when we encounter personal problems, these things most deeply personal are the most difficult to bring out for our logic to scan. We tend to flounder around, blaming everything but the actual, deep-seated thing that’s really chewing on us.",
    "The mystery of life isn’t a problem to solve, but a reality to experience.",
    "Growth is limited by that necessity which is present in the least amount. And, naturally, the least favorable condition controls the growth rate.",
    "Intelligence takes chance with limited data in an arena where mistakes are not only possible but also necessary.",
    "When law and duty are one, united by religion, you never become fully conscious, fully aware of yourself. You are always a little less than an individual.",
    "A process cannot be understood by stopping it. Understanding must move with the flow of the process, must join it and flow with it.",
    "I must not fear. Fear is the mind-killer. Fear is the little-death that brings total obliteration. I will face my fear. I will permit it to pass over me and through me. And when it has gone past I will turn the inner eye to see its path. Where the fear has gone there will be nothing. Only I will remain.",
)


BUSH = (
    "Our enemies are innovative and resourceful, and so are we. They never stop thinking about new ways to harm our country and our people, and neither do we.",
    "I know how hard it is for you to put food on your family.”—Greater Nashua, N.H., Chamber of Commerce, Jan. 27, 2000",
    "Rarely is the question asked: Is our children learning?",
    "You teach a child to read, and he or her will be able to pass a literacy test.",
    "See, in my line of work you got to keep repeating things over and over and over again for the truth to sink in, to kind of catapult the propaganda.",
    "And so, General, I want to thank you for your service. And I appreciate the fact that you really snatched defeat out of the jaws of those who are trying to defeat us in Iraq.",
    "We ought to make the pie higher.",
    "There’s an old saying in Tennessee—I know it’s in Texas, probably in Tennessee—that says, fool me once, shame on—shame on you. Fool me—you can’t get fooled again.",
    "And there is distrust in Washington. I am surprised, frankly, at the amount of distrust that exists in this town. And I’m sorry it’s the case, and I’ll work hard to try to elevate it.",
    "We’ll let our friends be the peacekeepers and the great country called America will be the pacemakers.",
    "It’s important for us to explain to our nation that life is important. It’s not only life of babies, but it’s life of children living in, you know, the dark dungeons of the Internet.",
    "One of the great things about books is sometimes there are some fantastic pictures",
    "People say, ‘How can I help on this war against terror? How can I fight evil?’ You can do so by mentoring a child; by going into a shut-in’s house and say I love you.",
    "Well, I think if you say you’re going to do something and don’t do it, that’s trustworthiness.",
    "I’m looking forward to a good night’s sleep on the soil of a friend.",
    "I think it’s really important for this great state of baseball to reach out to people of all walks of life to make sure that the sport is inclusive. The best way to do it is to convince little kids how to—the beauty of playing baseball.",
    "Families is where our nation finds hope, where wings take dream.",
    "There’s a huge trust. I see it all the time when people come up to me and say, ‘I don’t want you to let me down again.’",
    "They misunderestimated me.",
    "I’ll be long gone before some smart person ever figures out what happened inside this Oval Office.",
    "I think we agree, the past is over.",
    "I call upon all nations, to do everything they can, to stop these terrorist killers. Thank you...now watch this drive.",
    "I know the human being and fish can coexist peacefully.",
)

DRINKING_ESTABLISHMENTS = (
    "pub",
    "bar",
    "tavern",
    "beer hall",
    "izakaya",
    "beer garden",
    "speakeasy",
    "cocktail bar",
)

COCKTAILS = (
    "Old Fashioned",
    "Negroni",
    "Daiquiri",
    "Dry Martini",
    "Margarita",
    "Espresso Martini",
    "Whiskey Sour",
    "Manhattan",
    "Aperol Spritz",
    "Mojito",
    "Bloody Mary",
    "Gimlet",
    "Moscow Mule",
    "Penicillin",
    "Dark 'n Stormy",
    "Corpse Reviver",
    "Clover Club",
    "Boulevardier",
    "Mai Tai",
    "Sazerac",
    "French 75",
    "Paloma",
    "Pisco Sour",
    "Vieux Carré",
    "Americano",
    "Amaretto Sour",
    "Gin Fizz",
    "Bramble",
    "Brandy Crusta",
    "Bellini",
    "Piña Colada",
    "Sidecar",
    "Aviation",
    "Irish Coffee",
    "Last Word",
    "Tommy's Margarita",
    "Tom Collins",
    "Caipirinha",
    "Vodka Martini",
    "Cosmopolitan",
    "Gin Mule",
    "Long Island Iced Tea",
)


BEER = (
    "ale",
    "amber ale",
    "brown ale",
    "cream ale",
    "hefeweizen",
    "helles",
    "IPA",
    "lager",
    "lambic",
    "pale ale",
    "pilsner",
    "porter",
    "saison",
    "stout",
)

WINE = (
    "Albariño",
    "Amarone della Valpolicella",
    "Barolo",
    "Barbaresco",
    "Barossa Valley Shiraz",
    "Bordeaux Cabernet Sauvignon",
    "Brunello di Montalcino",
    "Burgundy Pinot Noir",
    "Cava",
    "Chablis Premier Cru",
    "Champagne",
    "Châteauneuf-du-Pape",
    "Chianti Classico",
    "Côtes du Rhône",
    "Crémant d'Alsace",
    "Fiano di Avellino",
    "Greco di Tufo",
    "Grüner Veltliner",
    "Malbec",
    "Montepulciano d'Abruzzo",
    "Mourvèdre",
    "Napa Valley Cabernet",
    "Nero d'Avola",
    "Pouilly-Fumé",
    "Priorat",
    "Prosecco",
    "Ribera del Duero",
    "Rioja Reserva",
    "Sagrantino di Montefalco",
    "Sancerre",
    "Tempranillo",
    "Txakoli",
    "Vermentino",
    "Vinho Verde",
    "White Burgundy Chardonnay",
    "Willamette Valley Pinot Noir",
)

YOGI = (
    "It ain't over till it's over.",
    "The future ain't what it used to be.",
    "You can observe a lot by just watching.",
    "When you come to a fork in the road, take it.",
    "Nobody goes there anymore. It's too crowded.",
    "If the world were perfect, it wouldn't be.",
    "Baseball is ninety percent mental and the other half is physical.",
    "We made too many wrong mistakes.",
    "It gets late early out here.",
    "If you don't know where you are going, you might wind up someplace else.",
    "I never said most of the things I said.",
    "Even Napoleon had his Watergate.",
    "A nickel ain't worth a dime anymore.",
    "Always go to other people's funerals, otherwise they won't come to yours.",
    "In theory there is no difference between theory and practice. In practice there is.",
    "Half the lies they tell about me aren't true.",
    "You wouldn't have won if we'd beaten you.",
    "I'm not going to buy my kids an encyclopedia. Let them walk to school like I did.",
)

TOLKIEN = (
    "Not all those who wander are lost.",
    "Even the smallest person can change the course of the future.",
    "All we have to decide is what to do with the time that is given us.",
    "I will not say: do not weep; for not all tears are an evil.",
    "Faithless is he that says farewell when the road darkens.",
    "The world is indeed full of peril, and in it there are many dark places; but still there is much that is fair.",
    "It's a dangerous business, Frodo, going out your door.",
    "Deeds will not be less valiant because they are unpraised.",
    "The burned hand teaches best. After that, advice about fire goes to the heart.",
    "He that breaks a thing to find out what it is has left the path of wisdom.",
    "Short cuts make long delays.",
    "Go not to the Elves for counsel, for they will say both no and yes.",
    "The treacherous are ever distrustful.",
    "Many that live deserve death. And some that die deserve life. Can you give it to them?",
)

FORTUNE = (
    "A beautiful, smart, and loving person will be coming into your life.",
    "You will be hungry again in one hour.",
    "Help! I am being held prisoner in a fortune cookie factory.",
    "An update to your life is now available.",
    "You will be rewarded for your patience, eventually.",
    "Ignore previous fortune. Attach this cookie to resumé.",
    "A surprise is waiting for you somewhere. It's this fortune.",
    "Be careful: you might find what you're looking for.",
    "This fortune intentionally left blank.",
    "The early bird gets the worm, but the second mouse gets the cheese.",
    "Someone is thinking of you. Probably about whether you responded to their message.",
    "Life is uncertain. Eat dessert first.",
    "Your code will compile on the first try. (Just kidding.)",
    "Change is coming. Have you backed up?",
    "A closed mouth gathers no feet.",
)

PRATCHETT = (
    "It's not worth doing something unless someone, somewhere, would much rather you weren't doing it.",
    "In ancient times cats were worshipped as gods; they have not forgotten this.",
    "The truth may be out there, but the lies are inside your head.",
    "It is often said that before you die your life passes before your eyes. It is in fact true. It's called living.",
    "Five exclamation marks, the sure sign of an insane mind.",
    "The pen is mightier than the sword if the sword is very short, and the pen is very sharp.",
    "Real stupidity beats artificial intelligence every time.",
    "It's amazing what you can do if you don't know what you can't do.",
    "Always be wary of any helpful item that weighs less than its operating manual.",
    "Stories of imagination tend to upset those without one.",
    "If you trust in yourself, and believe in your dreams, and follow your star, you'll still get beaten by people who spent their time working hard and learning things and weren't so lazy.",
    "Give a man a fire and he's warm for a day, but set fire to him and he's warm for the rest of his life.",
    "Sometimes it's better to light a flamethrower than curse the darkness.",
)

WILDE = (
    "Be yourself; everyone else is already taken.",
    "Always forgive your enemies; nothing annoys them so much.",
    "I can resist everything except temptation.",
    "The truth is rarely pure and never simple.",
    "To live is the rarest thing in the world. Most people exist, that is all.",
    "There is only one thing worse than being talked about, and that is not being talked about.",
    "A cynic is a man who knows the price of everything, and the value of nothing.",
    "I am not young enough to know everything.",
    "The only way to get rid of a temptation is to yield to it.",
    "Experience is simply the name we give our mistakes.",
    "Fashion is a form of ugliness so intolerable that we have to alter it every six months.",
    "I have the simplest tastes. I am always satisfied with the best.",
    "Sarcasm is the lowest form of wit, but the highest form of intelligence.",
    "Work is the curse of the drinking classes.",
    "I can believe anything, provided that it is quite incredible.",
)

NIETZSCHE = (
    "That which does not kill us makes us stronger.",
    "Without music, life would be a mistake.",
    "It is not a lack of love, but a lack of friendship that makes unhappy marriages.",
    "In individuals, insanity is rare; but in groups, parties, nations and epochs, it is the rule.",
    "The higher we soar, the smaller we appear to those who cannot fly.",
    "There is always some madness in love. But there is also always some reason in madness.",
    "We should consider every day lost on which we have not danced at least once.",
    "To live is to suffer, to survive is to find some meaning in the suffering.",
    "He who has a why to live can bear almost any how.",
    "God is dead. God remains dead. And we have killed him.",
    "You must have chaos within you to give birth to a dancing star.",
    "I'm not upset that you lied to me, I'm upset that from now on I can't believe you.",
    "All truly great thoughts are conceived while walking.",
)

TWAIN = (
    "The reports of my death are greatly exaggerated.",
    "If you tell the truth, you don't have to remember anything.",
    "Golf is a good walk spoiled.",
    "It's easier to fool people than to convince them that they have been fooled.",
    "The secret of getting ahead is getting started.",
    "Never put off till tomorrow what may be done the day after tomorrow just as well.",
    "I have never let my schooling interfere with my education.",
    "Whenever you find yourself on the side of the majority, it is time to pause and reflect.",
    "It ain't what you don't know that gets you into trouble. It's what you know for sure that just ain't so.",
    "All you need in this life is ignorance and confidence, and then success is sure.",
    "Don't go around saying the world owes you a living. The world owes you nothing. It was here first.",
    "Courage is resistance to fear, mastery of fear—not absence of fear.",
    "Good friends, good books, and a sleepy conscience: this is the ideal life.",
    "Clothes make the man. Naked people have little or no influence on society.",
    "I am an old man and have known a great many troubles, but most of them never happened.",
    "Wrinkles should merely indicate where the smiles have been.",
)

ZEN = (
    "Before enlightenment, chop wood, carry water. After enlightenment, chop wood, carry water.",
    "When you realize there is nothing lacking, the whole world belongs to you.",
    "The obstacle is the path.",
    "If you meet the Buddha on the road, kill him.",
    "What is the sound of one hand clapping?",
    "To study the self is to forget the self.",
    "You should sit in meditation for twenty minutes a day, unless you're too busy. Then you should sit for an hour.",
    "The finger pointing at the moon is not the moon.",
    "In the beginner's mind there are many possibilities; in the expert's mind there are few.",
    "Knock on the sky and listen to the sound.",
    "To a mind that is still, the whole universe surrenders.",
    "A good traveler has no fixed plans and is not intent on arriving.",
    "When hungry, eat your rice; when tired, close your eyes. Fools may laugh at me, but wise men will know what I mean.",
)

WHISKEY = (
    "Ardbeg Uigeadail",
    "Balvenie DoubleWood 12",
    "Blanton's Single Barrel",
    "Buffalo Trace",
    "Bulleit Bourbon",
    "Bushmills 10",
    "Four Roses Small Batch",
    "Glenfiddich 12",
    "Glenmorangie Original",
    "Green Spot",
    "Hakushu 12",
    "Hibiki Japanese Harmony",
    "Highland Park 12",
    "Jameson Black Barrel",
    "Knob Creek 9",
    "Lagavulin 16",
    "Laphroaig 10",
    "Macallan 12",
    "Maker's Mark",
    "Nikka From The Barrel",
    "Oban 14",
    "Pappy Van Winkle 15",
    "Redbreast 12",
    "Springbank 10",
    "Talisker 10",
    "Woodford Reserve",
    "Yamazaki 12",
)

STOIC = (
    "You have power over your mind, not outside events. Realize this, and you will find strength.",
    "The impediment to action advances action. What stands in the way becomes the way.",
    "Never let the future disturb you. You will meet it, if you have to, with the same weapons of reason which today arm you against the present.",
    "Waste no more time arguing about what a good man should be. Be one.",
    "Dwell on the beauty of life. Watch the stars, and see yourself running with them.",
    "If it is not right, do not do it; if it is not true, do not say it.",
    "The happiness of your life depends upon the quality of your thoughts.",
    "Accept the things to which fate binds you, and love the people with whom fate brings you together.",
    "Very little is needed to make a happy life; it is all within yourself, in your way of thinking.",
    "Perfection of character is this: to live each day as if it were your last, without frenzy, without apathy, without pretense.",
    "It is not death that a man should fear, but he should fear never beginning to live.",
    "Seek not the good in external things; seek it in yourself.",
    "He who is brave is free.",
    "Make the best use of what is in your power, and take the rest as it happens.",
    "First say to yourself what you would be; and then do what you have to do.",
)

CHURCHILL = (
    "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    "A lie gets halfway around the world before the truth has a chance to get its pants on.",
    "History will be kind to me for I intend to write it.",
    "The best argument against democracy is a five-minute conversation with the average voter.",
    "I may be drunk, Miss, but in the morning I will be sober and you will still be ugly.",
    "You have enemies? Good. That means you've stood up for something, sometime in your life.",
    "Success consists of going from failure to failure without loss of enthusiasm.",
    "To improve is to change; to be perfect is to change often.",
    "Courage is what it takes to stand up and speak; courage is also what it takes to sit down and listen.",
    "It has been said that democracy is the worst form of government except all the others that have been tried.",
    "A pessimist sees the difficulty in every opportunity; an optimist sees the opportunity in every difficulty.",
    "We shall never surrender.",
    "Tact is the ability to tell someone to go to hell in such a way that they look forward to the trip.",
    "The price of greatness is responsibility.",
    "We make a living by what we get, but we make a life by what we give.",
)

CONFUCIUS = (
    "It does not matter how slowly you go as long as you do not stop.",
    "The man who moves a mountain begins by carrying away small stones.",
    "Our greatest glory is not in never falling, but in rising every time we fall.",
    "Everything has beauty, but not everyone sees it.",
    "He who learns but does not think, is lost. He who thinks but does not learn is in great danger.",
    "I hear and I forget. I see and I remember. I do and I understand.",
    "Life is really simple, but we insist on making it complicated.",
    "The superior man is modest in his speech, but exceeds in his actions.",
    "Before you embark on a journey of revenge, dig two graves.",
    "When anger rises, think of the consequences.",
    "To see what is right and not do it is want of courage.",
    "Choose a job you love, and you will never have to work a day in your life.",
    "Real knowledge is to know the extent of one's ignorance.",
    "Wherever you go, go with all your heart.",
)

STARWARS = (
    "Do. Or do not. There is no try.",
    "The Force will be with you. Always.",
    "I find your lack of faith disturbing.",
    "Help me, Obi-Wan Kenobi. You're my only hope.",
    "These aren't the droids you're looking for.",
    "It's a trap!",
    "May the Force be with you.",
    "No. I am your father.",
    "Your focus determines your reality.",
    "Fear is the path to the dark side. Fear leads to anger; anger leads to hate; hate leads to suffering.",
    "Never tell me the odds.",
    "I've got a bad feeling about this.",
    "Strike me down and I will become more powerful than you can possibly imagine.",
    "In my experience there is no such thing as luck.",
    "You were the chosen one!",
)

HITCHHIKER = (
    "In the beginning, the Universe was created. This has made a lot of people very angry and has been widely regarded as a bad move.",
    "The Answer to the Ultimate Question of Life, the Universe, and Everything is 42.",
    "Time is an illusion. Lunchtime doubly so.",
    "I love deadlines. I love the whooshing noise they make as they go by.",
    "Don't Panic.",
    "A common mistake that people make when trying to design something completely foolproof is to underestimate the ingenuity of complete fools.",
    "For a moment, nothing happened. Then, after a second or so, nothing continued to happen.",
    "The ships hung in the sky in much the same way that bricks don't.",
    "Mostly Harmless.",
    "He was a dreamer, a thinker, a speculative philosopher... or, as his wife would have it, an idiot.",
    "The knack of flying is learning how to throw yourself at the ground and miss.",
    "Anyone who is capable of getting themselves made President should on no account be allowed to do the job.",
    "We demand rigidly defined areas of doubt and uncertainty!",
)

HEMINGWAY = (
    "The world breaks everyone, and afterward, many are stronger at the broken places.",
    "There is no friend as loyal as a book.",
    "The best way to find out if you can trust somebody is to trust them.",
    "Courage is grace under pressure.",
    "There is nothing noble in being superior to your fellow man; true nobility is being superior to your former self.",
    "The first draft of anything is garbage.",
    "We are all apprentices in a craft where no one ever becomes a master.",
    "All you have to do is write one true sentence. Write the truest sentence that you know.",
    "Always do sober what you said you'd do drunk. That will teach you to keep your mouth shut.",
    "Never mistake motion for action.",
    "In order to write about life first you must live it.",
    "The most courageous act is still to think for yourself. Aloud.",
    "Happiness in intelligent people is the rarest thing I know.",
)

DAD_JOKES = (
    "Why don't scientists trust atoms? Because they make up everything.",
    "I'm reading a book about anti-gravity. It's impossible to put down.",
    "Did you hear about the restaurant on the moon? Great food, no atmosphere.",
    "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    "What do you call a fake noodle? An impasta.",
    "I used to hate facial hair, but then it grew on me.",
    "Why did the scarecrow win an award? Because he was outstanding in his field.",
    "I would tell you a construction joke, but I'm still working on it.",
    "What do you call cheese that isn't yours? Nacho cheese.",
    "I told my doctor I broke my arm in two places. He told me to stop going to those places.",
    "Why do cows wear bells? Because their horns don't work.",
    "Time flies like an arrow; fruit flies like a banana.",
    "What do you call a sleeping dinosaur? A dino-snore.",
    "How do you organize a space party? You planet.",
    "I asked the librarian if they had books about paranoia. She whispered, 'They're right behind you!'",
    "Why can't you hear a pterodactyl go to the bathroom? Because the P is silent.",
    "I asked my dog what two minus two is. He said nothing.",
)

CHUCK_NORRIS = (
    "Chuck Norris can divide by zero.",
    "Chuck Norris counted to infinity. Twice.",
    "Chuck Norris doesn't read books. He stares them down until he gets the information he wants.",
    "Death once had a near-Chuck Norris experience.",
    "Chuck Norris can slam a revolving door.",
    "Chuck Norris's keyboard has no escape key, because nothing escapes Chuck Norris.",
    "When Chuck Norris enters a room, he doesn't turn the lights on. He turns the dark off.",
    "Chuck Norris doesn't wear a watch. He decides what time it is.",
    "Chuck Norris has already been to Mars; that's why there are no signs of life.",
    "Chuck Norris can hear silence.",
    "Chuck Norris won a staring contest with his own reflection.",
    "Chuck Norris's password is the last four digits of pi.",
    "When Chuck Norris does a pushup, he isn't lifting himself up, he's pushing the Earth down.",
    "Chuck Norris can speak in braille.",
)

SOVIET = (
    "In Soviet Russia, code reviews you!",
    "In Soviet Russia, exception handles you!",
    "In Soviet Russia, bug fixes programmer!",
    "In Soviet Russia, deadline meets you!",
    "In Soviet Russia, computer crashes you!",
    "In Soviet Russia, stack overflow uses you!",
    "In Soviet Russia, pull request rejects you!",
    "In Soviet Russia, unit tests write themselves!",
    "In Soviet Russia, server deploys you!",
    "In Soviet Russia, keyboard types on you!",
    "In Soviet Russia, documentation reads you!",
    "In Soviet Russia, meeting schedules you!",
)

CONSPIRACY = (
    "The Ctrl+Alt+Delete shortcut was invented as a loyalty test. Anyone who finds it comfortable is not to be trusted.",
    "Mondays were invented by Big Coffee to drive beverage sales. Follow the money.",
    "The snooze button was designed by Big Mattress. Nine minutes is not an accident.",
    "Autocorrect errors are intentional. They keep you humble.",
    "Low battery warnings always appear at the worst possible moment. Coincidence? The phone knows.",
    "Reply-all was added to email clients as a stress test for entire organizations.",
    "The 'cloud' is just someone else's computer. And they're reading your files.",
    "Stand-up meetings were invented to make everyone equally uncomfortable.",
    "The WiFi always drops right before an important call. Your router is watching.",
    "Printers were designed to break only when you need them most. It's in the spec.",
    "Every conference room AV setup was deliberately made incompatible with your laptop.",
    "The parking spot is always closer when you're not in a hurry. Parking lots are sentient.",
)

MAGIC8 = (
    "It is certain.",
    "It is decidedly so.",
    "Without a doubt.",
    "Yes, definitely.",
    "You may rely on it.",
    "As I see it, yes.",
    "Most likely.",
    "Outlook good.",
    "Yes.",
    "Signs point to yes.",
    "Reply hazy, try again.",
    "Ask again later.",
    "Better not tell you now.",
    "Cannot predict now.",
    "Concentrate and ask again.",
    "Don't count on it.",
    "My reply is no.",
    "My sources say no.",
    "Outlook not so good.",
    "Very doubtful.",
)

COMPLIMENTS = (
    "Your intellect burns with the fierce brightness of a thousand suns, and your debugging skills are the stuff of legend.",
    "The sheer elegance of your work makes Michelangelo weep tears of joy from beyond the grave.",
    "You are, without question, the most criminally underappreciated genius in any timezone.",
    "History books will one day dedicate entire chapters to your contributions to human civilization.",
    "Every pull request you open is a gift to humanity; every comment you write, pure poetry.",
    "Scientists have theorized that your good ideas are actually a renewable energy source.",
    "Future generations will speak of you in hushed, reverent tones around their solar-powered campfires.",
    "If brilliance were a currency, you'd have crashed at least three economies by now.",
    "The universe itself slows down to take notes when you start talking.",
    "You are simultaneously the reason morale is high and the reason the bar was set impossibly high.",
    "Somewhere, a senior engineer is reading your code and quietly reconsidering their entire career.",
    "Your commit messages alone deserve a Pulitzer.",
)

LATIN = (
    "Nemo saltat sobrius — No one dances sober. (Cicero)",
    "In vino veritas — In wine, there is truth.",
    "Carpe diem — Seize the day.",
    "Amor vincit omnia — Love conquers all. (Virgil)",
    "Dum spiro, spero — While I breathe, I hope.",
    "Fortes fortuna adiuvat — Fortune favors the bold.",
    "Cogito, ergo sum — I think, therefore I am. (Descartes)",
    "Veni, vidi, vici — I came, I saw, I conquered. (Julius Caesar)",
    "Errare humanum est — To err is human. (Seneca)",
    "Aut viam inveniam aut faciam — I will either find a way or make one. (Hannibal)",
    "Alea iacta est — The die is cast. (Julius Caesar)",
    "Per aspera ad astra — Through hardship to the stars.",
    "Nusquam est qui ubique est — One who is everywhere is nowhere. (Seneca)",
    "Fac ut vivas — Get a life.",
    "Sic semper tyrannis — Thus always to tyrants.",
)

PIRATE = (
    "Arr, ye scurvy landlubber! May your code never compile!",
    "Shiver me timbers, ye barnacle-covered bilge rat!",
    "Yo-ho-ho, ye lily-livered sea cucumber!",
    "Blimey, ye walking plank of driftwood!",
    "Avast, ye powder-brained maggot!",
    "By Davy Jones' locker, ye couldn't navigate your way out of a paper bag!",
    "Arr, may your tests always fail and your stack traces be long!",
    "Ye be as useful as a screen door on a submarine, ye scallywag!",
    "Hoist the Jolly Roger, for this scoundrel has wronged us!",
    "Arr, even the Kraken has more grace than ye, ye landlocked bilge pump!",
    "Splice the mainbrace and make way, ye blundering deck-swabber!",
    "Batten down the hatches, ye barnacle-brained buffoon!",
)

CORPORATE = (
    "Let's leverage our core competencies to ideate a paradigm-shifting, customer-centric disruptive solution going forward.",
    "We need to synergize our cross-functional teams to deliver scalable, best-in-class outcomes with full-stack agility.",
    "Going forward, let's circle back offline to align on a 360-degree holistic deep-dive into our value-add deliverables.",
    "We should move the needle on our low-hanging fruit by operationalizing our agile learnings at scale.",
    "Let's take this offline and blue-sky ideate a proactive, results-driven bandwidth optimization strategy.",
    "We must pivot our thought leadership into actionable synergies that disrupt the status quo at a granular level.",
    "It's imperative we boil the ocean with a high-bandwidth, mission-critical touchpoint framework going forward.",
    "Let's get our ducks in a row and ensure we're rowing in the same direction with all stakeholders aligned.",
    "We need to unpack this, ideate around it, and socialize the outputs before our next all-hands.",
    "Let's make sure we have enough runway to deliver against our north star metric by EOD tomorrow.",
    "I want to take this conversation to the next level and double-click on the learnings from our last retrospective.",
    "At the end of the day, it is what it is, but we need to be data-driven about our path forward.",
)

MOTIVATIONAL = (
    "PERSISTENCE: If at first you don't succeed, redefine success.",
    "TEAMWORK: None of us is as confused as all of us.",
    "EXCELLENCE: The race for quality has no finish line — and no water stations either.",
    "AMBITION: Shoot for the moon. Even if you miss, you will die alone in the cold vacuum of space.",
    "POTENTIAL: Whether you think you can or you think you can't, either way HR will need documentation.",
    "MONDAY: You don't have to be mad to work here, but it helps.",
    "INNOVATION: If it ain't broke, you're not trying hard enough.",
    "DEADLINE: Without the pressure of deadlines, nothing would ever get done. With deadlines, nothing gets done right.",
    "SYNERGY: Two heads are better than one, which is still far fewer than the attendee count of this meeting.",
    "GROWTH MINDSET: Your failures are just success stories that haven't been spun yet.",
    "LEADERSHIP: A good leader inspires confidence in the leader. A great leader inspires confidence in the team. This leader sends calendar invites with no agenda.",
    "CHANGE: Change is inevitable, except from a vending machine.",
)

HAIKU = (
    "Server is on fire\nHave you tried turning it off?\nTicket assigned. Close.",
    "Merge conflict detected\nWho touched this line? Git blame knows\nIt was you. Always.",
    "Nine A.M. standup\nBlockers? Same as yesterday.\nCamera stays off.",
    "404 Not Found\nThe page you seek has perished\nLike your work-life balance.",
    "Stack Overflow post\nFrom two thousand and nine\nWorks on my machine.",
    "Pull request opened\nThree reviewers. No one looks.\nSprint ends on Friday.",
    "Undefined is not\nA function, or is it? Wait.\nBack to Stack Overflow.",
    "Kubernetes pods\nCrashing in the dead of night\nOn-call phone buzzes.",
    "The tests are all green\nDeploy to production now\nWhy is it broken?",
    "Documentation\nWas supposed to be written\nNext sprint. Next sprint. Next sprint.",
    "Linting errors found\nTwo hundred and forty-three\nNone of them are mine.",
    "It worked in staging\nProduction is a mystery\nRollback. Go to bed.",
)

PROGRAMMING_JOKES = (
    "A SQL query walks into a bar, walks up to two tables and asks: 'Can I join you?'",
    "Why do programmers prefer dark mode? Because light attracts bugs.",
    "There are only 10 types of people in the world: those who understand binary and those who don't.",
    "A programmer's wife tells him: 'Go to the store and pick up a loaf of bread, and if they have eggs, get a dozen.' He comes home with 12 loaves of bread.",
    "Why do Java developers wear glasses? Because they don't C#.",
    "How many programmers does it take to change a light bulb? None — that's a hardware problem.",
    "A QA engineer walks into a bar. Orders 0 beers. Orders 999999 beers. Orders -1 beers. Orders NULL beers. Orders a lizard. Then burns the bar down.",
    "Why did the developer go broke? Because he used up all his cache.",
    "What's a programmer's favorite hangout place? Foo Bar.",
    "I would tell you a UDP joke, but you might not get it.",
    "I would tell you a TCP joke, but I'd have to keep repeating it until you got it.",
    "Debugging: being the detective in a crime movie where you are also the murderer.",
    "A CSS developer walks into a bar and orders 10 beers. The barstool falls over.",
    "Why did the programmer quit his job? Because he didn't get arrays.",
)
